### ISSUE TITLE
PunctuatedAssigner in chapter 6 is not accurate

### ISSUE THREAD

**Issue by bithw1** [streaming-with-flink/examples-scala#3]
The code is:
`
class PunctuatedAssigner extends AssignerWithPunctuatedWatermarks[SensorReading] {

  // 1 min in ms
  val bound: Long = 60 * 1000

  override def checkAndGetNextWatermark(r: SensorReading, extractedTS: Long): Watermark = {
    if (r.id == "sensor_1") {
      // emit watermark if reading is from sensor_1
      new Watermark(extractedTS - bound)
    } else {
      // do not emit a watermark
      null
    }
  }

  override def extractTimestamp(r: SensorReading, previousTS: Long): Long = {
    // assign record timestamp
    r.timestamp
  }
}
`

The Watermark got from `checkAndGetNextWatermark` may go backwards, that is, the largest watermark seen so far should be remembered, and compare `new Watermark(extractedTS - bound)` with this largest watermark to decide which to return.

**Comment by fhueske** [comment]
Thanks for opening this issue and your question @bithw1. 
In fact it is OK to provide watermarks that go backwards. Flink will compare a new watermark provided by a watermark generator with the current watermark and only forward the new watermark if it's timestamp is later than the current one. Watermarks that are earlier are simply ignored.

I'll close this issue, but please fell free to ask follow up questions or leave comments.

Thanks, Fabian

**Comment by bithw1** [comment]
Sure,thanks @fhueske for the helpful reply!
