### ISSUE TITLE
I would like to know which tool was used to draw the schematic diagram in this book, thank you

### ISSUE THREAD

**Issue by huangsheng7271** [streaming-with-flink/examples-scala#7]

**Comment by fhueske** [comment]
Hi @huangsheng7271,

The diagrams were produced by an illustrator of the publisher (O'Reilly Media).
I prepared sketches of the diagrams in the Google Doc drawing editor, but I don't know which tool was used to produce the final version.
Sorry that I couldn't help with this one.

Best, Fabian
